#!/usr/bin/env bash
# Generate a ssh key pair

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N betty

echo RSA key pair generated:
echo Private key saved as: ~/.ssh/school
echo Public key saved as: ~/.ssh/school.pub
